create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  booking_date date not null,
  slot text not null,
  name text not null,
  phone text not null,
  service text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists bookings_unique_date_slot
on public.bookings (booking_date, slot);

alter table public.bookings enable row level security;

grant usage on schema public to anon;
grant select, insert, delete on public.bookings to anon;
grant usage, select on sequence public.bookings_id_seq to anon;
grant usage on schema public to authenticated;
grant select, delete on public.bookings to authenticated;

drop policy if exists "public_can_read_bookings" on public.bookings;
create policy "public_can_read_bookings"
on public.bookings
for select
to anon
using (true);

drop policy if exists "public_can_insert_bookings" on public.bookings;
create policy "public_can_insert_bookings"
on public.bookings
for insert
to anon
with check (true);

drop policy if exists "public_can_delete_bookings" on public.bookings;
create policy "public_can_delete_bookings"
on public.bookings
for delete
to anon
using (true);

drop policy if exists "authenticated_can_delete_bookings" on public.bookings;
create policy "authenticated_can_delete_bookings"
on public.bookings
for delete
to authenticated
using (true);

update public.bookings
set service = split_part(service, ' | ', 1)
where service like '% | %';

update public.bookings
set service = regexp_replace(service, '\s+com\s+[^|]+$', '', 'i')
where service ~* '\s+com\s+[^|]+$';
